### ISSUE TITLE
Using the same function (ancestors()) duplicates

### ISSUE THREAD

**Issue by CodeWithDennis** [paxha/laravel-recursive-relationship#8]
So i am not sure if this is on my end but when i use `$category->ancestors();` on the same page twice it will duplicate the output and shows all the ancestors twice.

`count($category->ancestors());` will also do this

**Comment by paxha** [comment]
dears kindly share your code snippet where you are using this

**Comment by CodeWithDennis** [comment]
Laravel Blade File

```
@foreach($quoteRequest->category->ancestors()->reverse() as $key)
   <li class="breadcrumb-item text-muted">{{ $key->name }}</li>
@endforeach
```

If i call this `$quoteRequest->category->ancestors()` again on the page it will show all the categories twice.

**Comment by CodeWithDennis** [comment]
Example 1 (Correct):

```
@foreach($quoteRequest->category->ancestors()->reverse() as $key)
   <li class="breadcrumb-item text-muted">{{ $key->name }}</li>
@endforeach
```

**Output: Parent Category - Sub Category**

Example 2 (Incorrect)

```
 {{ count($quoteRequest->category->ancestors()) }} <-- Example
@foreach($quoteRequest->category->ancestors()->reverse() as $key)
   <li class="breadcrumb-item text-muted">{{ $key->name }}</li>
@endforeach
```

**Output: Parent Category - Parent Category - Sub Category**

**Comment by paxha** [comment]
Hey @Elsingad,
thanks for this information. there is a bug in the `ancestors`' fucntion code. I am going to fix it.

**Comment by CodeWithDennis** [comment]
Good to hear!

**Comment by CodeWithDennis** [comment]
Any news on this?
